linter:
  rules:
    - prefer_const_declarations
    - unnecessary_getters_setters
    - unnecessary_await_in_return
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - file_names
    - empty_statements
    - await_only_futures
    - avoid_print
    - avoid_empty_else
    - always_put_required_named_parameters_first
    - valid_regexps
    - use_rethrow_when_possible
    - unnecessary_this
    - unnecessary_statements
    - unnecessary_parenthesis
    - unnecessary_overrides
    - unnecessary_null_in_if_null_operators
    - unnecessary_new
    - unnecessary_const
    - unnecessary_brace_in_string_interps
    - unawaited_futures
    - sort_pub_dependencies
    - overridden_fields
    - list_remove_unrelated_type
    - no_duplicate_case_values
    - avoid_unused_constructor_parameters